- .gitignore
- build.js
- package.json
- yarn.lock
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/1)
> Add: babelify

- development/test-create-react-app-default-bundler.sh
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/7)
> Fix: sed script in ci test

- src/abi/HexStream.js
- src/abi/coder.js
- src/abi/index.js
- src/contract/Contract.js
- src/contract/ContractEvent.js
- src/contract/ContractFunction.js
- src/util/format.js
- test/abi/abi.test.js
- test/contract/contract.json
- test/contract/contract.test.js
- test/util/format.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/9)
> FIX: '0xa' as hex

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/14)
> Fix GitHub security warnings

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/15)
> fix acorn dependencies

- api.md
- package.json
- src/abi/coder.js
- src/abi/index.js
- src/contract/Contract.js
- src/contract/ContractABICoder.js
- src/contract/ContractEvent.js
- src/contract/ContractOverride.js
- src/util/unit.js
- test/abi/abi.test.js
- test/abi/coder.test.js
- test/contract/contract.json
- test/contract/contract.test.js
- test/util/unit.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/12)
> FIX:abi of tuple[]

- mock/MockProvider.js
- package.json
- src/Account.js
- src/Conflux.js
- src/Message.js
- src/util/format.js
- test/conflux/conflux.after.test.js
- test/conflux/conflux.before.test.js
- test/contract/contract.test.js
- test/message.test.js
- test/util/format.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/18)
> Message.sign/recover and rpc fileds name change

- example/code/conflux.js
- src/util/format.js
- src/util/unit.js
- test/util/format.test.js
- test/util/unit.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/22)
> FIX: unit return string

- mock/MockProvider.js
- package.json
- src/util/format.js
- test/conflux/conflux.after.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/23)
> format storageLimit, chainId, epochHeight

- src/abi/coder.js
- src/util/format.js
- test/abi/coder.test.js
- test/util/format.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/24)
> FIX: abi implicitly converting string to number

- api.md
- src/Conflux.js
- src/util/format.js
- test/account.test.js
- test/conflux/conflux.after.test.js
- test/conflux/conflux.before.test.js
- test/contract/contract.test.js
- test/transaction.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/27)
> add defaultStorageLimit defaultChainId

- .circleci/config.yml
----
need to add sdk to circle ci
https://app.circleci.com/projects/project-dashboard/github/Conflux-Chain/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/29)
> Add: trigger developer-site build

- development/build-frontend.js
- package.json
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/36)
> Fix: browserify circular require

- development/build-frontend.js
related discussion https://forum.conflux.fun/t/topic/1045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/46)
> fix: include crypto into browserify build

- README.md
- development/build-frontend.js
- package.json
- yarn.lock
resolve #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/48)
> fix: broken sourcemap

- CHANGE_LOG.md
- README.md
- development/build-frontend.js
- mock/MockProvider.js
- package-lock.json
- package.json
- src/Conflux.js
- src/util/format.js
- test/conflux/conflux.before.test.js
- types/index.d.ts
- types/rpc.d.ts
- types/tsconfig.json
- yarn.lock
Type definition will be useful, when projects developing with typescript that have use `js-conflux-sdk`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/43)
> Add TypeScript type definition

- mock/MockProvider.js
- package-lock.json
- src/Conflux.js
- src/util/format.js
- test/conflux/conflux.before.test.js
- types/index.d.ts
- types/rpc.d.ts
- types/tsconfig.json
FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/51)
> Add ts type defination

- CHANGE_LOG.md
- api.md
- package.json
- src/Account.js
- src/Conflux.js
- test/account.test.js
- test/conflux/conflux.before.test.js
- types/index.d.ts
- yarn.lock
* create Account from privateKey or publicKey or address, 
* sendTransaction `from` fields accept both Account instance or privateKey hex
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/44)
> ADD: create Account by privateKey or publicKey or address, `from` accept fields accept privateKey

- CHANGE_LOG.md
- api.md
- mock/MockProvider.js
- package.json
- src/Conflux.js
- test/conflux/conflux.before.test.js
- test/conflux/conflux.test.js
- test/contract/contract.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/52)
> UPDATE: fix default value for cfx_call and cfx_estimateGasAndCollateral

- CHANGE_LOG.md
- api.md
- src/Conflux.js
- test/conflux/conflux.before.test.js
- test/conflux/conflux.test.js
- test/subscribe.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/53)
> DELETE: remove defaultGas, defaultStorageLimit

- CHANGE_LOG.md
- api.md
- mock/MockProvider.js
- src/Conflux.js
- src/util/format.js
- test/conflux/conflux.before.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/61)
> UPDATE: RPC returned all number as hex

- CHANGE_LOG.md
- package.json
- src/Account.js
- test/account.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/68)
> FIX: keystore address drop '0x'

- README.md
- mock/MockProvider.js
- src/Conflux.js
- test/conflux/conflux.before.test.js
FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/69)
> update readme add detail usage and update send_transaction method

- mock/MockProvider.js
- src/Conflux.js
- src/util/format.js
- test/conflux/conflux.after.test.js
Reverts Conflux-Chain/js-conflux-sdk#74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/76)
> Revert "add one rpc checkBalanceAgainstTx"

- src/contract/abi/ArrayCoder.js
- src/contract/abi/BoolCoder.js
- src/contract/abi/BytesCoder.js
- src/contract/abi/IntegerCoder.js
- src/contract/abi/StringCoder.js
- src/contract/abi/TupleCoder.js
- src/contract/abi/index.js
- src/provider/WebSocketProvider.js
- test/conflux/after.test.js
- test/contract/EventCoder.test.js
- test/contract/FunctionCoder.test.js
- test/contract/contract.test.js
- test/contract/valueCoder.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/86)
> FIX: EventCoder FunctionCoder valueCoder return JSBI

- README.md
- docs/getting_start.md
- docs/how_to_send_tx.md
- docs/interact_with_contract.md
- docs/quick_intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/87)
> add more documentation

- .eslintrc.js
- CHANGE_LOG.md
- api.md
- src/CONST.js
- src/Drip.js
- src/provider/WebSocketProvider.js
- test/provider.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/88)
> FIX: use w3cwebsocket for WebSocketProvider

- README.md
- api.md
- docs/getting_start.md
- docs/how_to_send_tx.md
- docs/interact_with_contract.md
- package.json
- src/CONST.js
- src/Conflux.js
- src/contract/Contract.js
- src/contract/abi/BoolCoder.js
- src/contract/abi/IntegerCoder.js
- src/provider/WebSocketProvider.js
- src/util/format.js
- src/util/jsbi.js
- test/conflux/after.test.js
- test/contract/EventCoder.test.js
- test/contract/FunctionCoder.test.js
- test/contract/contract.test.js
- test/contract/valueCoder.test.js
- test/util/format.test.js
- test/util/jsbi.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/89)
> UPDATE: use BigInt for nodejs, JSBI for browser

- docs/api.md
- scripts/document.js
- src/Conflux.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/93)
> UPDATE: update conflux.getAccount doc without break line

- CHANGE_LOG.md
- src/provider/BaseProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/94)
> fix: update request id avoid repeat

- CHANGE_LOG.md
- docs/api.md
- src/provider/WebSocketProvider.js
- src/util/format.js
- src/util/parser.js
- test/conflux/before.test.js
- test/drip.test.js
- test/util/format.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/96)
> Ws and parser

- docs/api.md
- mock/MockProvider.js
- src/Conflux.js
- src/util/format.js
- test/conflux/after.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/98)
> ADD: getSupplyInfo

- CHANGE_LOG.md
- docs/api.md
- docs/faqs.md
- docs/how_to_send_tx.md
- docs/interact_with_contract.md
- docs/overview.md
- docs/todo.md
- src/Conflux.js
- src/util/format.js
- src/util/sign.js
trace_block need conflux node open specify settings, and can be used to get block execution trace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/103)
> add method `trace_block`

- CHANGE_LOG.md
- example/wrapProvider/index.html
- package.json
- src/Conflux.js
- src/index.js
- src/util/address.js
- src/util/format.js
- src/util/providerWrapper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/107)
> support new rpcs

- example/wrapProvider/index.html
- package.json
- src/util/providerWrapper.js
provider wrap params passing bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/109)
> fix provider wrap bug

- package.json
- types/index.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/116)
> update ts type definination

- CHANGE_LOG.md
- example/2_send_transaction.js
- example/wrapProvider/work-with-portal.html
- package.json
- src/Conflux.js
- src/Drip.js
- src/contract/abi/BytesCoder.js
- src/contract/standard/crc20.json
- src/contract/standard/index.js
- src/util/address.js
- src/util/format.js
- test/conflux/before.test.js
- test/contract/valueCoder.test.js
- test/util/format.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/117)
> add  method CRC20 to Conflux object to easy communicate with token 

- README.md
- change_log.md
- docs/api/Conflux.md
- docs/api/Contract.md
- docs/api/Drip.md
- docs/api/Misc.md
- docs/api/Provider.md
- docs/api/README.md
- docs/api/Subscribe.md
- docs/api/Transaction.md
- docs/api/Wallet.md
- docs/api/utils.md
- docs/conflux_checksum_address.md
- docs/interact_with_contract.md
- scripts/document.js
- src/Conflux.js
- src/util/format.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/122)
> Pending tx

- change_log.md
- package-lock.json
- package.json
- src/util/address.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/123)
> Optimize address convert performance

- src/util/namedTuple.js
- test/contract/valueCoder.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/125)
> FIX: NamedTuple constructor(0) as [0]

- src/util/callable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/130)
> FIX: call override with umd

- .travis.yml
- SUMMARY.md
- bin/cfxjs.js
- change_log.md
- docs/FAQs.md
- docs/account.md
- docs/interact_with_contract.md
- package-lock.json
- package.json
- src/Conflux.js
- src/util/address.js
- src/util/format.js
- src/util/index.js
- test/contract/contract.test.js
- test/util/format.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/131)
> Misc updates

- change_log.md
- package.json
- src/Conflux.js
- src/contract/Contract.js
- src/contract/abi/BytesCoder.js
- src/util/format.js
- types/index.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/135)
> Abi decode return hex string for bytesN data

- README.md
- change_log.md
- src/Conflux.js
- src/util/format.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/137)
> support methods add in conflux-rust v1.1.5

- SUMMARY.md
- docs/providers.md
- docs/sign_methods.md
- docs/utilities.md
- package-lock.json
- package.json
- src/Message.js
- src/PersonalMessage.js
- src/contract/Contract.js
- src/contract/abi/ArrayCoder.js
- src/index.js
- src/provider/RPCError.js
- test/personalMessage.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)
> Add support for personal_sign.

- docs/interact_with_contract.md
- package.json
- src/util/address.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/148)
> export more address utils

- change_log.md
- package.json
- src/Conflux.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/146)
> feat: add balance in rst of estimateGasAndCollateralAdvance
